apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autorele
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: bb-helmdemo
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "flux-system:bbimgpolicy:name"}
      tag: 6.1.1 # {"$imagepolicy": "flux-system:bbimgpolicy:tag"}
